version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'railway'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'ExjEyUiGJhYIcWoBJAncGSdhqXNMTLDH'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'ExjEyUiGJhYIcWoBJAncGSdhqXNMTLDH'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '43201:43201'
    expose:
      # Opens port 3306 on the container
      - '43201'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: